// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-bookstore using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=checkError_e75f941bf5
ROOST_METHOD_SIG_HASH=checkError_e49b9fc736

FUNCTION_DEF=func checkError(err error)
Scenario 1: Error is nil

Details:
  Description: This test is meant to check if the function behaves as expected when the error passed to it is nil. In this case, the function should not print any error message and should not exit the program.
Execution:
  Arrange: Create a nil error.
  Act: Invoke the checkError function with the nil error.
  Assert: Use Go testing facilities to verify that no error message is printed and the program does not exit.
Validation:
  The assertion is based on the fact that the function should not react to a nil error. This test is important to ensure that the function does not cause unnecessary program exits or print error messages when there is no error.

Scenario 2: Error is not nil

Details:
  Description: This test is meant to check if the function behaves as expected when the error passed to it is not nil. In this case, the function should print the error message and exit the program.
Execution:
  Arrange: Create a non-nil error.
  Act: Invoke the checkError function with the non-nil error.
  Assert: Use Go testing facilities to verify that the error message is printed and the program exits.
Validation:
  The assertion is based on the fact that the function should react to a non-nil error by printing the error message and exiting the program. This test is important to ensure that the function correctly handles errors and exits the program when necessary.

Scenario 3: Error with custom message

Details:
  Description: This test is meant to check if the function prints the correct error message when the error passed to it has a custom message. In this case, the function should print the custom error message and exit the program.
Execution:
  Arrange: Create a non-nil error with a custom message.
  Act: Invoke the checkError function with the non-nil error.
  Assert: Use Go testing facilities to verify that the custom error message is printed and the program exits.
Validation:
  The assertion is based on the fact that the function should print the custom error message when the error passed to it has a custom message. This test is important to ensure that the function correctly prints custom error messages.
*/

// ********RoostGPT********

package bookstore

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"testing"
)

func TestCheckError(t *testing.T) {

	testCases := []struct {
		name          string
		err           error
		expectedError string
	}{
		{
			name:          "Error is nil",
			err:           nil,
			expectedError: "",
		},
		{
			name:          "Error is not nil",
			err:           errors.New("test error"),
			expectedError: "Error Happened test error\n",
		},
		{
			name:          "Error with custom message",
			err:           errors.New("custom error message"),
			expectedError: "Error Happened custom error message\n",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			oldStdout := os.Stdout
			r, w, _ := os.Pipe()
			os.Stdout = w

			checkError(tc.err)

			os.Stdout = oldStdout

			outC := make(chan string)
			go func() {
				var buf bytes.Buffer
				fmt.Fscanf(r, "%s", &buf)
				outC <- buf.String()
			}()
			out := <-outC

			if out != tc.expectedError {
				t.Errorf("Expected error message '%s', but got '%s'", tc.expectedError, out)
			}
		})
	}
}
