// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-bookstore using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=saveBooks_f944094c1b
ROOST_METHOD_SIG_HASH=saveBooks_1fdb6f7496

FUNCTION_DEF=func saveBooks(books [ // save books to books.json file
]Book) error
Scenario 1: Successful Saving of Books to JSON File

Details:
  Description: This test is meant to check if the function can successfully save a list of books into a JSON file. The target scenario is when the function is given a valid list of books.

Execution:
  Arrange: Create a slice of Book structs with valid data.
  Act: Invoke the saveBooks function with the created slice of books.
  Assert: Use Go testing facilities to verify that the JSON file was created and contains the correct data.

Validation:
  The choice of assertion is to check if the file was created and if it contains the correct data. The logic behind the expected result is that the function should be able to create a JSON file and write the correct data into it. This test is important as it checks the main functionality of the function.

Scenario 2: Error Handling When Unable to Marshal Books

Details:
  Description: This test is meant to check if the function can handle errors when it is unable to marshal the list of books into JSON. The target scenario is when the function is given a list of books that cannot be marshaled into JSON.

Execution:
  Arrange: Create a slice of Book structs with invalid data that cannot be marshaled into JSON.
  Act: Invoke the saveBooks function with the created slice of books.
  Assert: Use Go testing facilities to verify that the function returns an error.

Validation:
  The choice of assertion is to check if the function returns an error. The logic behind the expected result is that the function should return an error when it is unable to marshal the list of books into JSON. This test is important as it checks the function's error handling capabilities.

Scenario 3: Error Handling When Unable to Write to File

Details:
  Description: This test is meant to check if the function can handle errors when it is unable to write to the JSON file. The target scenario is when the function is unable to write to the file due to reasons such as lack of permissions.

Execution:
  Arrange: Create a slice of Book structs with valid data and set up the environment such that the function does not have permissions to write to the file.
  Act: Invoke the saveBooks function with the created slice of books.
  Assert: Use Go testing facilities to verify that the function returns an error.

Validation:
  The choice of assertion is to check if the function returns an error. The logic behind the expected result is that the function should return an error when it is unable to write to the file. This test is important as it checks the function's error handling capabilities.
*/

// ********RoostGPT********

package bookstore

import (
	"encoding/json"
	"io/ioutil"
	"os"
	"testing"
)

func TestSaveBooks(t *testing.T) {

	testCases := []struct {
		name     string
		books    []Book
		wantErr  bool
		filePath string
	}{
		{
			name: "Successful Saving of Books to JSON File",
			books: []Book{
				{Id: "1", Title: "Book1", Author: "Author1", Price: "100", Imageurl: "url1"},
				{Id: "2", Title: "Book2", Author: "Author2", Price: "200", Imageurl: "url2"},
			},
			wantErr:  false,
			filePath: "./books.json",
		},
		{
			name: "Error Handling When Unable to Marshal Books",
			books: []Book{
				{Id: "1", Title: "", Author: "Author1", Price: "100", Imageurl: "url1"},
			},
			wantErr:  true,
			filePath: "./books.json",
		},
		{
			name: "Error Handling When Unable to Write to File",
			books: []Book{
				{Id: "1", Title: "Book1", Author: "Author1", Price: "100", Imageurl: "url1"},
			},
			wantErr:  true,
			filePath: "/invalid/path/books.json",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			err := saveBooks(tc.books)

			if (err != nil) != tc.wantErr {
				t.Errorf("saveBooks() error = %v, wantErr %v", err, tc.wantErr)
				return
			}

			if !tc.wantErr {

				if _, err := os.Stat(tc.filePath); os.IsNotExist(err) {
					t.Errorf("File %v should exist", tc.filePath)
				}

				fileBytes, err := ioutil.ReadFile(tc.filePath)
				if err != nil {
					t.Errorf("Failed to read file %v", tc.filePath)
				}

				var books []Book
				err = json.Unmarshal(fileBytes, &books)
				if err != nil {
					t.Errorf("Failed to unmarshal file content: %v", err)
				}

				for i, book := range books {
					if book != tc.books[i] {
						t.Errorf("Expected book %v, but got %v", tc.books[i], book)
					}
				}
			}
		})
	}
}
